// Copyright (c) 2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// source: IAM/AsyncAPI/client.yaml (0.1.0)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: accelbyte-asyncapi/iam/client/v1/client.proto

package client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientClientCreatedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientClientCreatedService/OnMessage"
)

// ClientClientCreatedServiceClient is the client API for ClientClientCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientCreated to the Client channel. (oneOf variant) (client ClientCreated)
type ClientClientCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientClientCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientClientCreatedServiceClient(cc grpc.ClientConnInterface) ClientClientCreatedServiceClient {
	return &clientClientCreatedServiceClient{cc}
}

func (c *clientClientCreatedServiceClient) OnMessage(ctx context.Context, in *ClientCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientClientCreatedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientClientCreatedServiceServer is the server API for ClientClientCreatedService service.
// All implementations should embed UnimplementedClientClientCreatedServiceServer
// for forward compatibility.
//
// Publishes a ClientCreated to the Client channel. (oneOf variant) (client ClientCreated)
type ClientClientCreatedServiceServer interface {
	OnMessage(context.Context, *ClientCreated) (*emptypb.Empty, error)
}

// UnimplementedClientClientCreatedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientClientCreatedServiceServer struct{}

func (UnimplementedClientClientCreatedServiceServer) OnMessage(context.Context, *ClientCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientClientCreatedServiceServer) testEmbeddedByValue() {}

// UnsafeClientClientCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientClientCreatedServiceServer will
// result in compilation errors.
type UnsafeClientClientCreatedServiceServer interface {
	mustEmbedUnimplementedClientClientCreatedServiceServer()
}

func RegisterClientClientCreatedServiceServer(s grpc.ServiceRegistrar, srv ClientClientCreatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientClientCreatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientClientCreatedService_ServiceDesc, srv)
}

func _ClientClientCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientClientCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientClientCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientClientCreatedServiceServer).OnMessage(ctx, req.(*ClientCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientClientCreatedService_ServiceDesc is the grpc.ServiceDesc for ClientClientCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientClientCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientClientCreatedService",
	HandlerType: (*ClientClientCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientClientCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientClientDeletedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientClientDeletedService/OnMessage"
)

// ClientClientDeletedServiceClient is the client API for ClientClientDeletedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientDeleted to the Client channel. (oneOf variant) (client ClientDeleted)
type ClientClientDeletedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientClientDeletedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientClientDeletedServiceClient(cc grpc.ClientConnInterface) ClientClientDeletedServiceClient {
	return &clientClientDeletedServiceClient{cc}
}

func (c *clientClientDeletedServiceClient) OnMessage(ctx context.Context, in *ClientDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientClientDeletedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientClientDeletedServiceServer is the server API for ClientClientDeletedService service.
// All implementations should embed UnimplementedClientClientDeletedServiceServer
// for forward compatibility.
//
// Publishes a ClientDeleted to the Client channel. (oneOf variant) (client ClientDeleted)
type ClientClientDeletedServiceServer interface {
	OnMessage(context.Context, *ClientDeleted) (*emptypb.Empty, error)
}

// UnimplementedClientClientDeletedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientClientDeletedServiceServer struct{}

func (UnimplementedClientClientDeletedServiceServer) OnMessage(context.Context, *ClientDeleted) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientClientDeletedServiceServer) testEmbeddedByValue() {}

// UnsafeClientClientDeletedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientClientDeletedServiceServer will
// result in compilation errors.
type UnsafeClientClientDeletedServiceServer interface {
	mustEmbedUnimplementedClientClientDeletedServiceServer()
}

func RegisterClientClientDeletedServiceServer(s grpc.ServiceRegistrar, srv ClientClientDeletedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientClientDeletedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientClientDeletedService_ServiceDesc, srv)
}

func _ClientClientDeletedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDeleted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientClientDeletedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientClientDeletedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientClientDeletedServiceServer).OnMessage(ctx, req.(*ClientDeleted))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientClientDeletedService_ServiceDesc is the grpc.ServiceDesc for ClientClientDeletedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientClientDeletedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientClientDeletedService",
	HandlerType: (*ClientClientDeletedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientClientDeletedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientClientUpdatedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientClientUpdatedService/OnMessage"
)

// ClientClientUpdatedServiceClient is the client API for ClientClientUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientUpdated to the Client channel. (oneOf variant) (client ClientUpdated)
type ClientClientUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientClientUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientClientUpdatedServiceClient(cc grpc.ClientConnInterface) ClientClientUpdatedServiceClient {
	return &clientClientUpdatedServiceClient{cc}
}

func (c *clientClientUpdatedServiceClient) OnMessage(ctx context.Context, in *ClientUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientClientUpdatedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientClientUpdatedServiceServer is the server API for ClientClientUpdatedService service.
// All implementations should embed UnimplementedClientClientUpdatedServiceServer
// for forward compatibility.
//
// Publishes a ClientUpdated to the Client channel. (oneOf variant) (client ClientUpdated)
type ClientClientUpdatedServiceServer interface {
	OnMessage(context.Context, *ClientUpdated) (*emptypb.Empty, error)
}

// UnimplementedClientClientUpdatedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientClientUpdatedServiceServer struct{}

func (UnimplementedClientClientUpdatedServiceServer) OnMessage(context.Context, *ClientUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientClientUpdatedServiceServer) testEmbeddedByValue() {}

// UnsafeClientClientUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientClientUpdatedServiceServer will
// result in compilation errors.
type UnsafeClientClientUpdatedServiceServer interface {
	mustEmbedUnimplementedClientClientUpdatedServiceServer()
}

func RegisterClientClientUpdatedServiceServer(s grpc.ServiceRegistrar, srv ClientClientUpdatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientClientUpdatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientClientUpdatedService_ServiceDesc, srv)
}

func _ClientClientUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientClientUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientClientUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientClientUpdatedServiceServer).OnMessage(ctx, req.(*ClientUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientClientUpdatedService_ServiceDesc is the grpc.ServiceDesc for ClientClientUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientClientUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientClientUpdatedService",
	HandlerType: (*ClientClientUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientClientUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientThirdPartyClientThirdPartyCreatedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyCreatedService/OnMessage"
)

// ClientThirdPartyClientThirdPartyCreatedServiceClient is the client API for ClientThirdPartyClientThirdPartyCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientThirdPartyCreated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyCreated)
type ClientThirdPartyClientThirdPartyCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientThirdPartyCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientThirdPartyClientThirdPartyCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientThirdPartyClientThirdPartyCreatedServiceClient(cc grpc.ClientConnInterface) ClientThirdPartyClientThirdPartyCreatedServiceClient {
	return &clientThirdPartyClientThirdPartyCreatedServiceClient{cc}
}

func (c *clientThirdPartyClientThirdPartyCreatedServiceClient) OnMessage(ctx context.Context, in *ClientThirdPartyCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientThirdPartyClientThirdPartyCreatedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientThirdPartyClientThirdPartyCreatedServiceServer is the server API for ClientThirdPartyClientThirdPartyCreatedService service.
// All implementations should embed UnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer
// for forward compatibility.
//
// Publishes a ClientThirdPartyCreated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyCreated)
type ClientThirdPartyClientThirdPartyCreatedServiceServer interface {
	OnMessage(context.Context, *ClientThirdPartyCreated) (*emptypb.Empty, error)
}

// UnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer struct{}

func (UnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer) OnMessage(context.Context, *ClientThirdPartyCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer) testEmbeddedByValue() {}

// UnsafeClientThirdPartyClientThirdPartyCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientThirdPartyClientThirdPartyCreatedServiceServer will
// result in compilation errors.
type UnsafeClientThirdPartyClientThirdPartyCreatedServiceServer interface {
	mustEmbedUnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer()
}

func RegisterClientThirdPartyClientThirdPartyCreatedServiceServer(s grpc.ServiceRegistrar, srv ClientThirdPartyClientThirdPartyCreatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientThirdPartyClientThirdPartyCreatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientThirdPartyClientThirdPartyCreatedService_ServiceDesc, srv)
}

func _ClientThirdPartyClientThirdPartyCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientThirdPartyCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientThirdPartyClientThirdPartyCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientThirdPartyClientThirdPartyCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientThirdPartyClientThirdPartyCreatedServiceServer).OnMessage(ctx, req.(*ClientThirdPartyCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientThirdPartyClientThirdPartyCreatedService_ServiceDesc is the grpc.ServiceDesc for ClientThirdPartyClientThirdPartyCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientThirdPartyClientThirdPartyCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyCreatedService",
	HandlerType: (*ClientThirdPartyClientThirdPartyCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientThirdPartyClientThirdPartyCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientThirdPartyClientThirdPartyDeletedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyDeletedService/OnMessage"
)

// ClientThirdPartyClientThirdPartyDeletedServiceClient is the client API for ClientThirdPartyClientThirdPartyDeletedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientThirdPartyDeleted to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyDeleted)
type ClientThirdPartyClientThirdPartyDeletedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientThirdPartyDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientThirdPartyClientThirdPartyDeletedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientThirdPartyClientThirdPartyDeletedServiceClient(cc grpc.ClientConnInterface) ClientThirdPartyClientThirdPartyDeletedServiceClient {
	return &clientThirdPartyClientThirdPartyDeletedServiceClient{cc}
}

func (c *clientThirdPartyClientThirdPartyDeletedServiceClient) OnMessage(ctx context.Context, in *ClientThirdPartyDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientThirdPartyClientThirdPartyDeletedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientThirdPartyClientThirdPartyDeletedServiceServer is the server API for ClientThirdPartyClientThirdPartyDeletedService service.
// All implementations should embed UnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer
// for forward compatibility.
//
// Publishes a ClientThirdPartyDeleted to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyDeleted)
type ClientThirdPartyClientThirdPartyDeletedServiceServer interface {
	OnMessage(context.Context, *ClientThirdPartyDeleted) (*emptypb.Empty, error)
}

// UnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer struct{}

func (UnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer) OnMessage(context.Context, *ClientThirdPartyDeleted) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer) testEmbeddedByValue() {}

// UnsafeClientThirdPartyClientThirdPartyDeletedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientThirdPartyClientThirdPartyDeletedServiceServer will
// result in compilation errors.
type UnsafeClientThirdPartyClientThirdPartyDeletedServiceServer interface {
	mustEmbedUnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer()
}

func RegisterClientThirdPartyClientThirdPartyDeletedServiceServer(s grpc.ServiceRegistrar, srv ClientThirdPartyClientThirdPartyDeletedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientThirdPartyClientThirdPartyDeletedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientThirdPartyClientThirdPartyDeletedService_ServiceDesc, srv)
}

func _ClientThirdPartyClientThirdPartyDeletedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientThirdPartyDeleted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientThirdPartyClientThirdPartyDeletedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientThirdPartyClientThirdPartyDeletedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientThirdPartyClientThirdPartyDeletedServiceServer).OnMessage(ctx, req.(*ClientThirdPartyDeleted))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientThirdPartyClientThirdPartyDeletedService_ServiceDesc is the grpc.ServiceDesc for ClientThirdPartyClientThirdPartyDeletedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientThirdPartyClientThirdPartyDeletedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyDeletedService",
	HandlerType: (*ClientThirdPartyClientThirdPartyDeletedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientThirdPartyClientThirdPartyDeletedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientThirdPartyClientThirdPartyUpdatedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyUpdatedService/OnMessage"
)

// ClientThirdPartyClientThirdPartyUpdatedServiceClient is the client API for ClientThirdPartyClientThirdPartyUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientThirdPartyUpdated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyUpdated)
type ClientThirdPartyClientThirdPartyUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientThirdPartyUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientThirdPartyClientThirdPartyUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientThirdPartyClientThirdPartyUpdatedServiceClient(cc grpc.ClientConnInterface) ClientThirdPartyClientThirdPartyUpdatedServiceClient {
	return &clientThirdPartyClientThirdPartyUpdatedServiceClient{cc}
}

func (c *clientThirdPartyClientThirdPartyUpdatedServiceClient) OnMessage(ctx context.Context, in *ClientThirdPartyUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientThirdPartyClientThirdPartyUpdatedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientThirdPartyClientThirdPartyUpdatedServiceServer is the server API for ClientThirdPartyClientThirdPartyUpdatedService service.
// All implementations should embed UnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer
// for forward compatibility.
//
// Publishes a ClientThirdPartyUpdated to the Client Third Party channel. (oneOf variant) (clientThirdParty ClientThirdPartyUpdated)
type ClientThirdPartyClientThirdPartyUpdatedServiceServer interface {
	OnMessage(context.Context, *ClientThirdPartyUpdated) (*emptypb.Empty, error)
}

// UnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer struct{}

func (UnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer) OnMessage(context.Context, *ClientThirdPartyUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer) testEmbeddedByValue() {}

// UnsafeClientThirdPartyClientThirdPartyUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientThirdPartyClientThirdPartyUpdatedServiceServer will
// result in compilation errors.
type UnsafeClientThirdPartyClientThirdPartyUpdatedServiceServer interface {
	mustEmbedUnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer()
}

func RegisterClientThirdPartyClientThirdPartyUpdatedServiceServer(s grpc.ServiceRegistrar, srv ClientThirdPartyClientThirdPartyUpdatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientThirdPartyClientThirdPartyUpdatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientThirdPartyClientThirdPartyUpdatedService_ServiceDesc, srv)
}

func _ClientThirdPartyClientThirdPartyUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientThirdPartyUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientThirdPartyClientThirdPartyUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientThirdPartyClientThirdPartyUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientThirdPartyClientThirdPartyUpdatedServiceServer).OnMessage(ctx, req.(*ClientThirdPartyUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientThirdPartyClientThirdPartyUpdatedService_ServiceDesc is the grpc.ServiceDesc for ClientThirdPartyClientThirdPartyUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientThirdPartyClientThirdPartyUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientThirdPartyClientThirdPartyUpdatedService",
	HandlerType: (*ClientThirdPartyClientThirdPartyUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientThirdPartyClientThirdPartyUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientPermissionsClientPermissionsCreatedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsCreatedService/OnMessage"
)

// ClientPermissionsClientPermissionsCreatedServiceClient is the client API for ClientPermissionsClientPermissionsCreatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientPermissionCreated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsCreated)
type ClientPermissionsClientPermissionsCreatedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientPermissionCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientPermissionsClientPermissionsCreatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientPermissionsClientPermissionsCreatedServiceClient(cc grpc.ClientConnInterface) ClientPermissionsClientPermissionsCreatedServiceClient {
	return &clientPermissionsClientPermissionsCreatedServiceClient{cc}
}

func (c *clientPermissionsClientPermissionsCreatedServiceClient) OnMessage(ctx context.Context, in *ClientPermissionCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientPermissionsClientPermissionsCreatedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientPermissionsClientPermissionsCreatedServiceServer is the server API for ClientPermissionsClientPermissionsCreatedService service.
// All implementations should embed UnimplementedClientPermissionsClientPermissionsCreatedServiceServer
// for forward compatibility.
//
// Publishes a ClientPermissionCreated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsCreated)
type ClientPermissionsClientPermissionsCreatedServiceServer interface {
	OnMessage(context.Context, *ClientPermissionCreated) (*emptypb.Empty, error)
}

// UnimplementedClientPermissionsClientPermissionsCreatedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientPermissionsClientPermissionsCreatedServiceServer struct{}

func (UnimplementedClientPermissionsClientPermissionsCreatedServiceServer) OnMessage(context.Context, *ClientPermissionCreated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientPermissionsClientPermissionsCreatedServiceServer) testEmbeddedByValue() {}

// UnsafeClientPermissionsClientPermissionsCreatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientPermissionsClientPermissionsCreatedServiceServer will
// result in compilation errors.
type UnsafeClientPermissionsClientPermissionsCreatedServiceServer interface {
	mustEmbedUnimplementedClientPermissionsClientPermissionsCreatedServiceServer()
}

func RegisterClientPermissionsClientPermissionsCreatedServiceServer(s grpc.ServiceRegistrar, srv ClientPermissionsClientPermissionsCreatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientPermissionsClientPermissionsCreatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientPermissionsClientPermissionsCreatedService_ServiceDesc, srv)
}

func _ClientPermissionsClientPermissionsCreatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientPermissionCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPermissionsClientPermissionsCreatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPermissionsClientPermissionsCreatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPermissionsClientPermissionsCreatedServiceServer).OnMessage(ctx, req.(*ClientPermissionCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientPermissionsClientPermissionsCreatedService_ServiceDesc is the grpc.ServiceDesc for ClientPermissionsClientPermissionsCreatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientPermissionsClientPermissionsCreatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientPermissionsClientPermissionsCreatedService",
	HandlerType: (*ClientPermissionsClientPermissionsCreatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientPermissionsClientPermissionsCreatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientPermissionsClientPermissionsDeletedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsDeletedService/OnMessage"
)

// ClientPermissionsClientPermissionsDeletedServiceClient is the client API for ClientPermissionsClientPermissionsDeletedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientPermissionDeleted to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsDeleted)
type ClientPermissionsClientPermissionsDeletedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientPermissionDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientPermissionsClientPermissionsDeletedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientPermissionsClientPermissionsDeletedServiceClient(cc grpc.ClientConnInterface) ClientPermissionsClientPermissionsDeletedServiceClient {
	return &clientPermissionsClientPermissionsDeletedServiceClient{cc}
}

func (c *clientPermissionsClientPermissionsDeletedServiceClient) OnMessage(ctx context.Context, in *ClientPermissionDeleted, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientPermissionsClientPermissionsDeletedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientPermissionsClientPermissionsDeletedServiceServer is the server API for ClientPermissionsClientPermissionsDeletedService service.
// All implementations should embed UnimplementedClientPermissionsClientPermissionsDeletedServiceServer
// for forward compatibility.
//
// Publishes a ClientPermissionDeleted to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsDeleted)
type ClientPermissionsClientPermissionsDeletedServiceServer interface {
	OnMessage(context.Context, *ClientPermissionDeleted) (*emptypb.Empty, error)
}

// UnimplementedClientPermissionsClientPermissionsDeletedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientPermissionsClientPermissionsDeletedServiceServer struct{}

func (UnimplementedClientPermissionsClientPermissionsDeletedServiceServer) OnMessage(context.Context, *ClientPermissionDeleted) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientPermissionsClientPermissionsDeletedServiceServer) testEmbeddedByValue() {}

// UnsafeClientPermissionsClientPermissionsDeletedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientPermissionsClientPermissionsDeletedServiceServer will
// result in compilation errors.
type UnsafeClientPermissionsClientPermissionsDeletedServiceServer interface {
	mustEmbedUnimplementedClientPermissionsClientPermissionsDeletedServiceServer()
}

func RegisterClientPermissionsClientPermissionsDeletedServiceServer(s grpc.ServiceRegistrar, srv ClientPermissionsClientPermissionsDeletedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientPermissionsClientPermissionsDeletedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientPermissionsClientPermissionsDeletedService_ServiceDesc, srv)
}

func _ClientPermissionsClientPermissionsDeletedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientPermissionDeleted)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPermissionsClientPermissionsDeletedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPermissionsClientPermissionsDeletedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPermissionsClientPermissionsDeletedServiceServer).OnMessage(ctx, req.(*ClientPermissionDeleted))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientPermissionsClientPermissionsDeletedService_ServiceDesc is the grpc.ServiceDesc for ClientPermissionsClientPermissionsDeletedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientPermissionsClientPermissionsDeletedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientPermissionsClientPermissionsDeletedService",
	HandlerType: (*ClientPermissionsClientPermissionsDeletedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientPermissionsClientPermissionsDeletedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}

const (
	ClientPermissionsClientPermissionsUpdatedService_OnMessage_FullMethodName = "/accelbyte.iam.client.v1.ClientPermissionsClientPermissionsUpdatedService/OnMessage"
)

// ClientPermissionsClientPermissionsUpdatedServiceClient is the client API for ClientPermissionsClientPermissionsUpdatedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Publishes a ClientPermissionUpdated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsUpdated)
type ClientPermissionsClientPermissionsUpdatedServiceClient interface {
	OnMessage(ctx context.Context, in *ClientPermissionUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientPermissionsClientPermissionsUpdatedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientPermissionsClientPermissionsUpdatedServiceClient(cc grpc.ClientConnInterface) ClientPermissionsClientPermissionsUpdatedServiceClient {
	return &clientPermissionsClientPermissionsUpdatedServiceClient{cc}
}

func (c *clientPermissionsClientPermissionsUpdatedServiceClient) OnMessage(ctx context.Context, in *ClientPermissionUpdated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientPermissionsClientPermissionsUpdatedService_OnMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientPermissionsClientPermissionsUpdatedServiceServer is the server API for ClientPermissionsClientPermissionsUpdatedService service.
// All implementations should embed UnimplementedClientPermissionsClientPermissionsUpdatedServiceServer
// for forward compatibility.
//
// Publishes a ClientPermissionUpdated to the Client Permissions channel. (oneOf variant) (clientPermissions ClientPermissionsUpdated)
type ClientPermissionsClientPermissionsUpdatedServiceServer interface {
	OnMessage(context.Context, *ClientPermissionUpdated) (*emptypb.Empty, error)
}

// UnimplementedClientPermissionsClientPermissionsUpdatedServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientPermissionsClientPermissionsUpdatedServiceServer struct{}

func (UnimplementedClientPermissionsClientPermissionsUpdatedServiceServer) OnMessage(context.Context, *ClientPermissionUpdated) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMessage not implemented")
}
func (UnimplementedClientPermissionsClientPermissionsUpdatedServiceServer) testEmbeddedByValue() {}

// UnsafeClientPermissionsClientPermissionsUpdatedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientPermissionsClientPermissionsUpdatedServiceServer will
// result in compilation errors.
type UnsafeClientPermissionsClientPermissionsUpdatedServiceServer interface {
	mustEmbedUnimplementedClientPermissionsClientPermissionsUpdatedServiceServer()
}

func RegisterClientPermissionsClientPermissionsUpdatedServiceServer(s grpc.ServiceRegistrar, srv ClientPermissionsClientPermissionsUpdatedServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientPermissionsClientPermissionsUpdatedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientPermissionsClientPermissionsUpdatedService_ServiceDesc, srv)
}

func _ClientPermissionsClientPermissionsUpdatedService_OnMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientPermissionUpdated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientPermissionsClientPermissionsUpdatedServiceServer).OnMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientPermissionsClientPermissionsUpdatedService_OnMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientPermissionsClientPermissionsUpdatedServiceServer).OnMessage(ctx, req.(*ClientPermissionUpdated))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientPermissionsClientPermissionsUpdatedService_ServiceDesc is the grpc.ServiceDesc for ClientPermissionsClientPermissionsUpdatedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientPermissionsClientPermissionsUpdatedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.iam.client.v1.ClientPermissionsClientPermissionsUpdatedService",
	HandlerType: (*ClientPermissionsClientPermissionsUpdatedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMessage",
			Handler:    _ClientPermissionsClientPermissionsUpdatedService_OnMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accelbyte-asyncapi/iam/client/v1/client.proto",
}
