// Copyright (c) 2023-2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.9
// source: service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Channel type enum for voice chat
type ChannelType int32

const (
	ChannelType_PARTY   ChannelType = 0
	ChannelType_TEAM    ChannelType = 1
	ChannelType_SESSION ChannelType = 2
)

// Enum value maps for ChannelType.
var (
	ChannelType_name = map[int32]string{
		0: "PARTY",
		1: "TEAM",
		2: "SESSION",
	}
	ChannelType_value = map[string]int32{
		"PARTY":   0,
		"TEAM":    1,
		"SESSION": 2,
	}
)

func (x ChannelType) Enum() *ChannelType {
	p := new(ChannelType)
	*p = x
	return p
}

func (x ChannelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ChannelType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ChannelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelType.Descriptor instead.
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// Request message for party token generation
type PartyTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`        // Path parameter: party ID
	HardMuted     bool                   `protobuf:"varint,2,opt,name=hard_muted,json=hardMuted,proto3" json:"hard_muted,omitempty"` // Query parameter: optional, default false
	Puid          string                 `protobuf:"bytes,3,opt,name=puid,proto3" json:"puid,omitempty"`                             // Optional, use provided Epic PUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyTokenRequest) Reset() {
	*x = PartyTokenRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyTokenRequest) ProtoMessage() {}

func (x *PartyTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyTokenRequest.ProtoReflect.Descriptor instead.
func (*PartyTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *PartyTokenRequest) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyTokenRequest) GetHardMuted() bool {
	if x != nil {
		return x.HardMuted
	}
	return false
}

func (x *PartyTokenRequest) GetPuid() string {
	if x != nil {
		return x.Puid
	}
	return ""
}

// Request message for session token generation (supports team and/or session)
type SessionTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`  // Path parameter: session ID
	Team          bool                   `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`                            // Generate team token
	Session       bool                   `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"`                      // Generate session token
	HardMuted     bool                   `protobuf:"varint,4,opt,name=hard_muted,json=hardMuted,proto3" json:"hard_muted,omitempty"` // Query parameter: optional, default false
	Puid          string                 `protobuf:"bytes,5,opt,name=puid,proto3" json:"puid,omitempty"`                             // Optional, use provided Epic PUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTokenRequest) Reset() {
	*x = SessionTokenRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTokenRequest) ProtoMessage() {}

func (x *SessionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTokenRequest.ProtoReflect.Descriptor instead.
func (*SessionTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *SessionTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionTokenRequest) GetTeam() bool {
	if x != nil {
		return x.Team
	}
	return false
}

func (x *SessionTokenRequest) GetSession() bool {
	if x != nil {
		return x.Session
	}
	return false
}

func (x *SessionTokenRequest) GetHardMuted() bool {
	if x != nil {
		return x.HardMuted
	}
	return false
}

func (x *SessionTokenRequest) GetPuid() string {
	if x != nil {
		return x.Puid
	}
	return ""
}

// Response message for single EOS token
type EOSTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientBaseUrl string                 `protobuf:"bytes,1,opt,name=client_base_url,json=clientBaseUrl,proto3" json:"client_base_url,omitempty"`                 // URL to join the voice room
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                                                        // Token to join voice room
	ChannelType   ChannelType            `protobuf:"varint,3,opt,name=channel_type,json=channelType,proto3,enum=voice.ChannelType" json:"channel_type,omitempty"` // Channel type: PARTY, TEAM, or SESSION
	RoomId        string                 `protobuf:"bytes,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                        // Epic voice chat room ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EOSTokenResponse) Reset() {
	*x = EOSTokenResponse{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EOSTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EOSTokenResponse) ProtoMessage() {}

func (x *EOSTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EOSTokenResponse.ProtoReflect.Descriptor instead.
func (*EOSTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *EOSTokenResponse) GetClientBaseUrl() string {
	if x != nil {
		return x.ClientBaseUrl
	}
	return ""
}

func (x *EOSTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EOSTokenResponse) GetChannelType() ChannelType {
	if x != nil {
		return x.ChannelType
	}
	return ChannelType_PARTY
}

func (x *EOSTokenResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// Response message for session token generation (array of tokens)
type SessionTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*EOSTokenResponse    `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"` // Array of generated tokens (team and/or session)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionTokenResponse) Reset() {
	*x = SessionTokenResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTokenResponse) ProtoMessage() {}

func (x *SessionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTokenResponse.ProtoReflect.Descriptor instead.
func (*SessionTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *SessionTokenResponse) GetTokens() []*EOSTokenResponse {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Request message for admin session token generation
type AdminSessionTokenRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`                            // Path parameter: session ID
	Team              bool                   `protobuf:"varint,2,opt,name=team,proto3" json:"team,omitempty"`                                                      // Generate team voice tokens
	Session           bool                   `protobuf:"varint,3,opt,name=session,proto3" json:"session,omitempty"`                                                // Generate session voice tokens
	HardMuted         bool                   `protobuf:"varint,4,opt,name=hard_muted,json=hardMuted,proto3" json:"hard_muted,omitempty"`                           // Optional, default false
	Notify            bool                   `protobuf:"varint,5,opt,name=notify,proto3" json:"notify,omitempty"`                                                  // Send notification to users
	AllowPendingUsers bool                   `protobuf:"varint,6,opt,name=allow_pending_users,json=allowPendingUsers,proto3" json:"allow_pending_users,omitempty"` // Include users with INVITED status (default: false)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminSessionTokenRequest) Reset() {
	*x = AdminSessionTokenRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSessionTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSessionTokenRequest) ProtoMessage() {}

func (x *AdminSessionTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSessionTokenRequest.ProtoReflect.Descriptor instead.
func (*AdminSessionTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *AdminSessionTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdminSessionTokenRequest) GetTeam() bool {
	if x != nil {
		return x.Team
	}
	return false
}

func (x *AdminSessionTokenRequest) GetSession() bool {
	if x != nil {
		return x.Session
	}
	return false
}

func (x *AdminSessionTokenRequest) GetHardMuted() bool {
	if x != nil {
		return x.HardMuted
	}
	return false
}

func (x *AdminSessionTokenRequest) GetNotify() bool {
	if x != nil {
		return x.Notify
	}
	return false
}

func (x *AdminSessionTokenRequest) GetAllowPendingUsers() bool {
	if x != nil {
		return x.AllowPendingUsers
	}
	return false
}

// Response message for a user's token
type AdminUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`             // AccelByte user ID
	VoiceToken    *EOSTokenResponse      `protobuf:"bytes,2,opt,name=voice_token,json=voiceToken,proto3" json:"voice_token,omitempty"` // Voice token response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUserTokenResponse) Reset() {
	*x = AdminUserTokenResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUserTokenResponse) ProtoMessage() {}

func (x *AdminUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUserTokenResponse.ProtoReflect.Descriptor instead.
func (*AdminUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *AdminUserTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AdminUserTokenResponse) GetVoiceToken() *EOSTokenResponse {
	if x != nil {
		return x.VoiceToken
	}
	return nil
}

// Response message for admin session token generation
type AdminSessionTokenResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Tokens        []*AdminUserTokenResponse `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"` // Tokens per user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSessionTokenResponse) Reset() {
	*x = AdminSessionTokenResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSessionTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSessionTokenResponse) ProtoMessage() {}

func (x *AdminSessionTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSessionTokenResponse.ProtoReflect.Descriptor instead.
func (*AdminSessionTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *AdminSessionTokenResponse) GetTokens() []*AdminUserTokenResponse {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// Request message for revoking tokens
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`    // Path parameter: room ID
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // List of AccelByte user IDs to revoke
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeTokenRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RevokeTokenRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// Response message for token revocation (empty for 204 No Content)
type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x05voice\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x10permission.proto\"a\n" +
	"\x11PartyTokenRequest\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1d\n" +
	"\n" +
	"hard_muted\x18\x02 \x01(\bR\thardMuted\x12\x12\n" +
	"\x04puid\x18\x03 \x01(\tR\x04puid\"\x95\x01\n" +
	"\x13SessionTokenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04team\x18\x02 \x01(\bR\x04team\x12\x18\n" +
	"\asession\x18\x03 \x01(\bR\asession\x12\x1d\n" +
	"\n" +
	"hard_muted\x18\x04 \x01(\bR\thardMuted\x12\x12\n" +
	"\x04puid\x18\x05 \x01(\tR\x04puid\"\xa0\x01\n" +
	"\x10EOSTokenResponse\x12&\n" +
	"\x0fclient_base_url\x18\x01 \x01(\tR\rclientBaseUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x125\n" +
	"\fchannel_type\x18\x03 \x01(\x0e2\x12.voice.ChannelTypeR\vchannelType\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\tR\x06roomId\"G\n" +
	"\x14SessionTokenResponse\x12/\n" +
	"\x06tokens\x18\x01 \x03(\v2\x17.voice.EOSTokenResponseR\x06tokens\"\xce\x01\n" +
	"\x18AdminSessionTokenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04team\x18\x02 \x01(\bR\x04team\x12\x18\n" +
	"\asession\x18\x03 \x01(\bR\asession\x12\x1d\n" +
	"\n" +
	"hard_muted\x18\x04 \x01(\bR\thardMuted\x12\x16\n" +
	"\x06notify\x18\x05 \x01(\bR\x06notify\x12.\n" +
	"\x13allow_pending_users\x18\x06 \x01(\bR\x11allowPendingUsers\"k\n" +
	"\x16AdminUserTokenResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\vvoice_token\x18\x02 \x01(\v2\x17.voice.EOSTokenResponseR\n" +
	"voiceToken\"R\n" +
	"\x19AdminSessionTokenResponse\x125\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1d.voice.AdminUserTokenResponseR\x06tokens\"H\n" +
	"\x12RevokeTokenRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"\x15\n" +
	"\x13RevokeTokenResponse\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*/\n" +
	"\vChannelType\x12\t\n" +
	"\x05PARTY\x10\x00\x12\b\n" +
	"\x04TEAM\x10\x01\x12\v\n" +
	"\aSESSION\x10\x022\xa7\x0e\n" +
	"\x05Voice\x12\x9e\x01\n" +
	"\vHealthCheck\x12\x19.voice.HealthCheckRequest\x1a\x1a.voice.HealthCheckResponse\"X\x92AC\n" +
	"\x05Voice\x12\fHealth check\x1a\x1fCheck if the service is healthy*\vHealthCheck\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/health\x12\xba\x02\n" +
	"\x12GeneratePartyToken\x12\x18.voice.PartyTokenRequest\x1a\x17.voice.EOSTokenResponse\"\xf0\x01\x92A\xc3\x01\n" +
	"\x05Voice\x12\x1aGenerate Party Voice Token\x1avGenerate an EOS voice token for a party voice channel. Validates user membership in the party before generating token.*\x18Voice_GeneratePartyTokenb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/public/party/{party_id}/token\x12\x8c\x03\n" +
	"\x14GenerateSessionToken\x12\x1a.voice.SessionTokenRequest\x1a\x1b.voice.SessionTokenResponse\"\xba\x02\x92A\x89\x02\n" +
	"\x05Voice\x12\x1cGenerate Session Voice Token\x1a\xb7\x01Generate EOS voice tokens for session and/or team channels. Set 'team' and/or 'session' flags to specify which tokens to generate. Returns an array of tokens based on requested types.*\x1aVoice_GenerateSessionTokenb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x82\xd3\xe4\x93\x02':\x01*\"\"/public/session/{session_id}/token\x12\xcb\x04\n" +
	"\x19GenerateAdminSessionToken\x12\x1f.voice.AdminSessionTokenRequest\x1a .voice.AdminSessionTokenResponse\"\xea\x03\x92A\x91\x03\n" +
	"\x05Voice\x12#Generate Admin Session Voice Tokens\x1a\xb3\x02Generate EOS voice tokens for all users in a session. Can include session and/or team tokens, and optionally send per-user notifications. Set allow_pending_users=true to include users who have been invited but not yet joined (status: INVITED). Requires ADMIN:NAMESPACE:{namespace}:VOICE [CREATE] permission.*\x1fVoice_GenerateAdminSessionTokenb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18!ADMIN:NAMESPACE:{namespace}:VOICE\x90\xb5\x18\x01\x82\xd3\xe4\x93\x02&:\x01*\"!/admin/session/{session_id}/token\x12\xe2\x02\n" +
	"\vRevokeToken\x12\x19.voice.RevokeTokenRequest\x1a\x1a.voice.RevokeTokenResponse\"\x9b\x02\x92A\xc1\x01\n" +
	"\x05Voice\x12\x12Revoke Voice Token\x1a\x82\x01Revoke voice tokens for specified users in a room. Admin endpoint requiring ADMIN:NAMESPACE:{namespace}:VOICE [DELETE] permission.*\x11Voice_RevokeTokenb\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00\x8a\xb5\x18!ADMIN:NAMESPACE:{namespace}:VOICE\x90\xb5\x18\b\x82\xd3\xe4\x93\x02':\x01*\"\"/admin/room/{room_id}/token/revokeB\xfe\x01\x92A\x9a\x01\x12 \n" +
	"\x19EOS Voice RTC Service API2\x031.0\"\n" +
	"/eos-voiceZ\x1f\n" +
	"\x1d\n" +
	"\x06Bearer\x12\x13\b\x02\x1a\rAuthorization \x02jI\n" +
	"\x05Voice\x12@EOS Voice RTC endpoints for generating and managing voice tokens\n" +
	" net.accelbyte.extend.eosvoicertcP\x01Z\x1bextend-eos-voice-rtc/pkg/pb\xaa\x02\x1cAccelByte.Extend.EosVoiceRtcb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_proto_goTypes = []any{
	(ChannelType)(0),                  // 0: voice.ChannelType
	(*PartyTokenRequest)(nil),         // 1: voice.PartyTokenRequest
	(*SessionTokenRequest)(nil),       // 2: voice.SessionTokenRequest
	(*EOSTokenResponse)(nil),          // 3: voice.EOSTokenResponse
	(*SessionTokenResponse)(nil),      // 4: voice.SessionTokenResponse
	(*AdminSessionTokenRequest)(nil),  // 5: voice.AdminSessionTokenRequest
	(*AdminUserTokenResponse)(nil),    // 6: voice.AdminUserTokenResponse
	(*AdminSessionTokenResponse)(nil), // 7: voice.AdminSessionTokenResponse
	(*RevokeTokenRequest)(nil),        // 8: voice.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),       // 9: voice.RevokeTokenResponse
	(*HealthCheckRequest)(nil),        // 10: voice.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 11: voice.HealthCheckResponse
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: voice.EOSTokenResponse.channel_type:type_name -> voice.ChannelType
	3,  // 1: voice.SessionTokenResponse.tokens:type_name -> voice.EOSTokenResponse
	3,  // 2: voice.AdminUserTokenResponse.voice_token:type_name -> voice.EOSTokenResponse
	6,  // 3: voice.AdminSessionTokenResponse.tokens:type_name -> voice.AdminUserTokenResponse
	10, // 4: voice.Voice.HealthCheck:input_type -> voice.HealthCheckRequest
	1,  // 5: voice.Voice.GeneratePartyToken:input_type -> voice.PartyTokenRequest
	2,  // 6: voice.Voice.GenerateSessionToken:input_type -> voice.SessionTokenRequest
	5,  // 7: voice.Voice.GenerateAdminSessionToken:input_type -> voice.AdminSessionTokenRequest
	8,  // 8: voice.Voice.RevokeToken:input_type -> voice.RevokeTokenRequest
	11, // 9: voice.Voice.HealthCheck:output_type -> voice.HealthCheckResponse
	3,  // 10: voice.Voice.GeneratePartyToken:output_type -> voice.EOSTokenResponse
	4,  // 11: voice.Voice.GenerateSessionToken:output_type -> voice.SessionTokenResponse
	7,  // 12: voice.Voice.GenerateAdminSessionToken:output_type -> voice.AdminSessionTokenResponse
	9,  // 13: voice.Voice.RevokeToken:output_type -> voice.RevokeTokenResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_permission_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
