// Copyright (c) 2023-2025 AccelByte Inc. All Rights Reserved.
// This is licensed software from AccelByte Inc, for limitations
// and restrictions contact your company contract manager.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.9
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Voice_HealthCheck_FullMethodName               = "/voice.Voice/HealthCheck"
	Voice_GeneratePartyToken_FullMethodName        = "/voice.Voice/GeneratePartyToken"
	Voice_GenerateSessionToken_FullMethodName      = "/voice.Voice/GenerateSessionToken"
	Voice_GenerateAdminSessionToken_FullMethodName = "/voice.Voice/GenerateAdminSessionToken"
	Voice_RevokeToken_FullMethodName               = "/voice.Voice/RevokeToken"
)

// VoiceClient is the client API for Voice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VoiceClient interface {
	// Health check endpoint
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Generate Party Voice Token
	GeneratePartyToken(ctx context.Context, in *PartyTokenRequest, opts ...grpc.CallOption) (*EOSTokenResponse, error)
	// Generate Session Voice Token (supports team and/or session tokens)
	GenerateSessionToken(ctx context.Context, in *SessionTokenRequest, opts ...grpc.CallOption) (*SessionTokenResponse, error)
	// Generate Admin Session Voice Tokens
	GenerateAdminSessionToken(ctx context.Context, in *AdminSessionTokenRequest, opts ...grpc.CallOption) (*AdminSessionTokenResponse, error)
	// Revoke Voice Token (Admin)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
}

type voiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVoiceClient(cc grpc.ClientConnInterface) VoiceClient {
	return &voiceClient{cc}
}

func (c *voiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Voice_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceClient) GeneratePartyToken(ctx context.Context, in *PartyTokenRequest, opts ...grpc.CallOption) (*EOSTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EOSTokenResponse)
	err := c.cc.Invoke(ctx, Voice_GeneratePartyToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceClient) GenerateSessionToken(ctx context.Context, in *SessionTokenRequest, opts ...grpc.CallOption) (*SessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionTokenResponse)
	err := c.cc.Invoke(ctx, Voice_GenerateSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceClient) GenerateAdminSessionToken(ctx context.Context, in *AdminSessionTokenRequest, opts ...grpc.CallOption) (*AdminSessionTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminSessionTokenResponse)
	err := c.cc.Invoke(ctx, Voice_GenerateAdminSessionToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *voiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, Voice_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoiceServer is the server API for Voice service.
// All implementations should embed UnimplementedVoiceServer
// for forward compatibility.
type VoiceServer interface {
	// Health check endpoint
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Generate Party Voice Token
	GeneratePartyToken(context.Context, *PartyTokenRequest) (*EOSTokenResponse, error)
	// Generate Session Voice Token (supports team and/or session tokens)
	GenerateSessionToken(context.Context, *SessionTokenRequest) (*SessionTokenResponse, error)
	// Generate Admin Session Voice Tokens
	GenerateAdminSessionToken(context.Context, *AdminSessionTokenRequest) (*AdminSessionTokenResponse, error)
	// Revoke Voice Token (Admin)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
}

// UnimplementedVoiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVoiceServer struct{}

func (UnimplementedVoiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedVoiceServer) GeneratePartyToken(context.Context, *PartyTokenRequest) (*EOSTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePartyToken not implemented")
}
func (UnimplementedVoiceServer) GenerateSessionToken(context.Context, *SessionTokenRequest) (*SessionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateSessionToken not implemented")
}
func (UnimplementedVoiceServer) GenerateAdminSessionToken(context.Context, *AdminSessionTokenRequest) (*AdminSessionTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateAdminSessionToken not implemented")
}
func (UnimplementedVoiceServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedVoiceServer) testEmbeddedByValue() {}

// UnsafeVoiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VoiceServer will
// result in compilation errors.
type UnsafeVoiceServer interface {
	mustEmbedUnimplementedVoiceServer()
}

func RegisterVoiceServer(s grpc.ServiceRegistrar, srv VoiceServer) {
	// If the following call panics, it indicates UnimplementedVoiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Voice_ServiceDesc, srv)
}

func _Voice_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voice_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voice_GeneratePartyToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServer).GeneratePartyToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voice_GeneratePartyToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServer).GeneratePartyToken(ctx, req.(*PartyTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voice_GenerateSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServer).GenerateSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voice_GenerateSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServer).GenerateSessionToken(ctx, req.(*SessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voice_GenerateAdminSessionToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSessionTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServer).GenerateAdminSessionToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voice_GenerateAdminSessionToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServer).GenerateAdminSessionToken(ctx, req.(*AdminSessionTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Voice_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Voice_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Voice_ServiceDesc is the grpc.ServiceDesc for Voice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Voice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voice.Voice",
	HandlerType: (*VoiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Voice_HealthCheck_Handler,
		},
		{
			MethodName: "GeneratePartyToken",
			Handler:    _Voice_GeneratePartyToken_Handler,
		},
		{
			MethodName: "GenerateSessionToken",
			Handler:    _Voice_GenerateSessionToken_Handler,
		},
		{
			MethodName: "GenerateAdminSessionToken",
			Handler:    _Voice_GenerateAdminSessionToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _Voice_RevokeToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
